CREATE TABLE "applicant_login" (
  "id"         BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  "aid"        BIGINT(20) UNSIGNED NOT NULL,
  "password"   VARCHAR(255) NOT NULL,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
)